name: Update AITubers Data and Deploy

on:
  schedule:
    - cron: '0 0,12 * * *'  # UTC時間の0時と12時（日本時間9時と21時）
  workflow_dispatch:  # 手動実行用

permissions:
  contents: write
  pages: write      # GitHub Pagesへのデプロイに必要
  id-token: write   # GitHub Pagesへのデプロイに必要

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client pytz

      - name: Update AITubers data
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python scripts/update_aitubers.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add app/data/aitubers.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update AITubers data" && git push origin main)

      # Next.jsのビルドとデプロイ
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
